--CREATE TABLE USUARIOS(
--ID INT PRIMARY KEY IDENTITY(1,1),
--USUARIO VARCHAR(50),
--NOMBRE VARCHAR(100)
--);

CREATE PROCEDURE INSERTAR_USUARIOS
@USUARIO VARCHAR(50),
@NOMBRE VARCHAR(100)
AS 
BEGIN
	INSERT INTO USUARIOS VALUES (@USUARIO, @NOMBRE)
END;

CREATE PROCEDURE EDITAR_USUARIOS
@ID INT,
@USUARIO VARCHAR(50),
@NOMBRE VARCHAR(100)
AS 
BEGIN
	UPDATE USUARIOS SET USUARIO = @USUARIO, NOMBRE=@NOMBRE WHERE ID  = @ID
END;

CREATE PROCEDURE ELIMINAR_USUARIOS
@ID INT
AS 
BEGIN
	DELETE FROM USUASRIOS WHERE ID  = @ID
END;

CREATE PROCEDURE CONSULTAR_USUARIOS
AS 
BEGIN
	SELECT ID, USUARIO, NOMBRE FROM USUARIOS
END;

CREATE PROCEDURE CONSULTAR_ID_USUARIOS
@ID INT
AS 
BEGIN
	SELECT ID, USUARIO, NOMBRE FROM USUARIOS WHERE ID = @ID
END;