--CREATE TABLE OPERACION_REALIZADA(
--ID INT PRIMARY KEY IDENTITY(1,1),
--OPERACION VARCHAR(100)
--);

CREATE PROCEDURE INSERTAR_OPERACIONES
@OPERACION VARCHAR(100)
AS
BEGIN
	INSERT INTO OPERACION_REALIZADA VALUES (@OPERACION)
END;

CREATE PROCEDURE EDITAR_OPERACIONES
@ID INT,
@OPERACION VARCHAR(100)
AS
BEGIN
	UPDATE OPERACION_REALIZADA SET OPERACION=@OPERACION WHERE ID = @ID
END;

CREATE PROCEDURE ELIMINAR_OPERACIONES
@ID INT
AS
BEGIN
	DELETE FROM OPERACION_REALIZADA WHERE ID = @ID
END;

CREATE PROCEDURE CONSULTAR_OPERACIONES
AS
BEGIN
	SELECT ID, OPERACION FROM OPERACION_REALIZADA
END;

CREATE PROCEDURE CONSULTAR_ID_OPERACIONES
@ID INT
AS
BEGIN
	SELECT ID, OPERACION FROM OPERACION_REALIZADA WHERE ID = @ID
END;