--CREATE TABLE OBSERVACIONES(
--ID INT PRIMARY KEY IDENTITY(1,1),
--OBSERVACIONES VARCHAR(100)
--);

CREATE PROCEDURE INSERTAR_OBSERVACIONES
@OBSERVACIONES VARCHAR(100)
AS
BEGIN
	INSERT INTO OBSERVACIONES VALUES (@OBSERVACIONES)
END;

CREATE PROCEDURE EDITAR_OBSERVACIONES
@ID INT,
@OBSERVACIONES VARCHAR(100)
AS
BEGIN
	UPDATE OBSERVACIONES SET OBSERVACIONES=@OBSERVACIONES WHERE ID = @ID
END;

CREATE PROCEDURE ELIMINAR_OBSERVACIONES
@ID INT
AS
BEGIN
	DELETE FROM OBSERVACIONES WHERE ID = @ID
END;

CREATE PROCEDURE CONSULTAR_OBSERVACIONES
AS
BEGIN
	SELECT ID, OBSERVACIONES FROM OBSERVACIONES
END;

CREATE PROCEDURE CONSULTAR_ID_OBSERVACIONES
@ID INT
AS
BEGIN
	SELECT ID, OBSERVACIONES FROM OBSERVACIONES WHERE ID = @ID
END;