CREATE DATABASE DESBLOQUEOS
USE DESBLOQUEOS

CREATE TABLE USUARIOS(
ID INT PRIMARY KEY IDENTITY(1,1),
USUARIO VARCHAR(50),
NOMBRE VARCHAR(100)
);

CREATE TABLE OPERACION_REALIZADA(
ID INT PRIMARY KEY IDENTITY(1,1),
OPERACION VARCHAR(100)
);

CREATE TABLE OBSERVACIONES(
ID INT PRIMARY KEY IDENTITY(1,1),
OBSERVACIONES VARCHAR(MAX)
);

CREATE TABLE OBSERVACION(
ID INT PRIMARY KEY IDENTITY(1,1),
OBSERVACION VARCHAR(MAX)
);

CREATE TABLE LISTA(
ID INT PRIMARY KEY IDENTITY(1,1),
LISTA VARCHAR(100)
);

CREATE TABLE CN(
ID INT PRIMARY KEY IDENTITY(1,1),
CN VARCHAR(100)
);

CREATE TABLE DESBLOQUEOS(
ID INT PRIMARY KEY IDENTITY(1,1),
USUARIO VARCHAR(50),
NOMBRE VARCHAR(500),
FECHA_CORREO DATE,
OPERACION_REALIZADA_1 VARCHAR(100),
FECHA_RESPUESTA_DESBLOQUEO DATE,
OPERACION_REALIZADA_2 VARCHAR(100),
FECHA_2 DATE,
OBSERVACIONES VARCHAR(MAX),
LISTA VARCHAR(100),
CN VARCHAR(100),
OBSERVACION VARCHAR(MAX),
FECHA_HORA_INGRESO DATETIME,
FECHA_HORA_RESPUESTA DATETIME,
TIEMPO_ATENCION DATETIME,
ACCIONISTA VARCHAR(MAX),
INFORMES_REGULATORIO VARCHAR(MAX),
ACC_RESULTADO VARCHAR(MAX)
);
