CREATE TABLE ESTADOS(
ID INT PRIMARY KEY IDENTITY,
NOMBRE_ESTADO VARCHAR(50)
);

CREATE PROCEDURE INSERTAR_ESTADOS
@ESTADO VARCHAR(50)
AS
BEGIN
	INSERT INTO ESTADOS VALUES (@ESTADO)
END

CREATE PROCEDURE EDITAR_ESTADOS
@ID INT,
@ESTADO VARCHAR(50)
AS
BEGIN
	UPDATE ESTADOS SET NOMBRE_ESTADO = @ESTADO
	WHERE ID = @ID
END

CREATE PROCEDURE CONSULTAR_ESTADOS
AS
BEGIN
	SELECT * FROM ESTADOS
END

CREATE PROCEDURE CONSULTAR_ID_ESTADOS
@ID INT
AS
BEGIN
	SELECT * FROM ESTADOS WHERE ID = @ID
END

CREATE PROCEDURE ELIMINAR_ESTADOS
@ID INT
AS
BEGIN
	DELETE FROM ESTADOS WHERE ID = @ID
END