CREATE DATABASE DESBLOQUEOS
USE DESBLOQUEOS

CREATE TABLE USUARIOS(
ID INT PRIMARY KEY IDENTITY(1,1),
USUARIO VARCHAR(50),
NOMBRE VARCHAR(100)
);

CREATE TABLE OPERACION_REALIZADA(
ID INT PRIMARY KEY IDENTITY(1,1),
OPERACION VARCHAR(100)
);

CREATE TABLE OBSERVACIONES(
ID INT PRIMARY KEY IDENTITY(1,1),
OBSERVACIONES VARCHAR(MAX)
);

CREATE TABLE OBSERVACION(
ID INT PRIMARY KEY IDENTITY(1,1),
OBSERVACION VARCHAR(MAX)
);

CREATE TABLE LISTA(
ID INT PRIMARY KEY IDENTITY(1,1),
LISTA VARCHAR(100)
);

CREATE TABLE CN(
ID INT PRIMARY KEY IDENTITY(1,1),
CN VARCHAR(100)
);

CREATE TABLE DESBLOQUEOS(
ID INT PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(500),
FECHA_CORREO DATETIME,
OPERACION_REALIZADA_1 VARCHAR(100),
FECHA_RESPUESTA_DESBLOQUEO DATETIME,
OBSERVACIONES VARCHAR(MAX),
LISTA VARCHAR(100),
CN VARCHAR(100),
OBSERVACION VARCHAR(MAX),
TIEMPO_ATENCION VARCHAR(10),
ACCIONISTA VARCHAR(5),
USUARIO_CREACION VARCHAR(50),
USUARIO_MODIFICACION VARCHAR(50),
FECHA_CREACION DATETIME,
FECHA_MODIFICACION DATETIME,
ESTADO VARCHAR(50)
);

CREATE TABLE ESTADOS(
ID INT PRIMARY KEY IDENTITY,
NOMBRE_ESTADO VARCHAR(50)
);
