/*CREATE TABLE DESBLOQUEOS(
ID INT PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(500),
FECHA_CORREO DATETIME,
OPERACION_REALIZADA_1 VARCHAR(100),
FECHA_RESPUESTA_DESBLOQUEO DATETIME,
OBSERVACIONES VARCHAR(MAX),
LISTA VARCHAR(100),
CN VARCHAR(100),
OBSERVACION VARCHAR(MAX),
TIEMPO_ATENCION VARCHAR(10),
ACCIONISTA VARCHAR(MAX),
USUARIO_CREACION VARCHAR(50),
USUARIO_MODIFICACION VARCHAR(50),
FECHA_CREACION DATETIME,
FECHA_MODIFICACION DATETIME,
ESTADO VARCHAR(50)
);
*/

CREATE PROCEDURE INSERTAR_DESBLOQUEOS
@NOMBRE VARCHAR(500),
@FECHA_CORREO DATETIME,
@OPERACION_REALIZADA_1 VARCHAR(100),
@FECHA_RESPUESTA_DESBLOQUEO DATETIME,
@OBSERVACIONES VARCHAR(MAX),
@LISTA VARCHAR(100),
@CN VARCHAR(100),
@OBSERVACION VARCHAR(MAX),
@ACCIONISTA VARCHAR(5),
@USUARIO_CREACION VARCHAR(50),
@ESTADO VARCHAR(50)
AS
BEGIN
INSERT INTO DESBLOQUEOS VALUES(	
								UPPER(@NOMBRE),
								@FECHA_CORREO,
								@OPERACION_REALIZADA_1,
								@FECHA_RESPUESTA_DESBLOQUEO,								
								@OBSERVACIONES,
								@LISTA,
								@CN,
								@OBSERVACION,
								CAST((DATEDIFF(MINUTE, @FECHA_CORREO, @FECHA_RESPUESTA_DESBLOQUEO) / 60) AS VARCHAR(2)) + ':' + RIGHT('0' + CAST((DATEDIFF(MINUTE, @FECHA_CORREO, @FECHA_RESPUESTA_DESBLOQUEO) % 60) AS VARCHAR(2)), 2),
								@ACCIONISTA,								
								UPPER(@USUARIO_CREACION),
								NULL,
								GETDATE(),
								NULL,
								@ESTADO
							)
END

CREATE PROCEDURE EDITAR_DESBLOQUEOS
@ID INT,
@NOMBRE VARCHAR(500),
@FECHA_CORREO DATETIME,
@OPERACION_REALIZADA_1 VARCHAR(100),
@FECHA_RESPUESTA_DESBLOQUEO DATETIME,
@OBSERVACIONES VARCHAR(MAX),
@LISTA VARCHAR(100),
@CN VARCHAR(100),
@OBSERVACION VARCHAR(MAX),
@ACCIONISTA VARCHAR(5),
@USUARIO_MODIFICACION VARCHAR(50),
@ESTADO VARCHAR(50)
AS
BEGIN
UPDATE  DESBLOQUEOS SET     
								NOMBRE = UPPER(@NOMBRE),
								FECHA_CORREO = @FECHA_CORREO,
								OPERACION_REALIZADA_1 = @OPERACION_REALIZADA_1,
								FECHA_RESPUESTA_DESBLOQUEO = @FECHA_RESPUESTA_DESBLOQUEO,								
								OBSERVACIONES = @OBSERVACIONES,
								LISTA = @LISTA,
								CN = @CN,
								OBSERVACION = @OBSERVACION,								
								TIEMPO_ATENCION = CAST((DATEDIFF(MINUTE, @FECHA_CORREO, @FECHA_RESPUESTA_DESBLOQUEO) / 60) AS VARCHAR(2)) + ':' + RIGHT('0' + CAST((DATEDIFF(MINUTE, @FECHA_CORREO, @FECHA_RESPUESTA_DESBLOQUEO) % 60) AS VARCHAR(2)), 2),
								ACCIONISTA = @ACCIONISTA,													
								USUARIO_MODIFICACION = UPPER(@USUARIO_MODIFICACION),								
								FECHA_MODIFICACION = GETDATE(),
								ESTADO = @ESTADO
WHERE ID = @ID
END

CREATE PROCEDURE ELIMINAR_DESBLOQUEOS
@ID INT
AS
BEGIN
DELETE FROM DESBLOQUEOS
WHERE ID = @ID
END

CREATE PROCEDURE CONSULTAR_ID_DESBLOQUEOS
@ID INT
AS
BEGIN
SELECT * FROM DESBLOQUEOS
WHERE ID = @ID
END

CREATE PROCEDURE CONSULTAR_DESBLOQUEOS
AS
BEGIN
SELECT * FROM DESBLOQUEOS
END


CREATE PROCEDURE CONSULTAR_NOMBRE_DESBLOQUEOS
@NOMBRE VARCHAR(500)
AS
BEGIN
SELECT * FROM DESBLOQUEOS
WHERE NOMBRE LIKE '%'+@NOMBRE+'%'
END

CREATE PROCEDURE CONSULTAR_DESBLOQUEOS_ASC
AS
BEGIN
SELECT * FROM DESBLOQUEOS ORDER BY ESTADO ASC
END

CREATE PROCEDURE CONSULTAR_DESBLOQUEOS_DES
AS
BEGIN
SELECT * FROM DESBLOQUEOS ORDER BY ESTADO DESC
END

